<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Javascript For Gallery, Javascript Simple Image Gallery" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body >
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/img1.jpg" alt="img1"  id="wows1_0"/></li>
<li><img src="data1/images/img2.jpg" alt="img2"  id="wows1_1"/></li>
<li><img src="data1/images/img3.jpg" alt="img3"  id="wows1_2"/></li>
<li><img src="data1/images/img4.jpg" alt="img4"  id="wows1_3"/></li>
<li><img src="data1/images/img5.jpg" alt="img5"  id="wows1_4"/></li>
<li><img src="data1/images/img6.jpg" alt="img6"  id="wows1_5"/></li>
<li><img src="data1/images/img7.jpg" alt="img7"  id="wows1_6"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="img1"><img src="data1/tooltips/img1.jpg" alt="img1"/>1</a>
<a href="#" title="img2"><img src="data1/tooltips/img2.jpg" alt="img2"/>2</a>
<a href="#" title="img3"><img src="data1/tooltips/img3.jpg" alt="img3"/>3</a>
<a href="#" title="img4"><img src="data1/tooltips/img4.jpg" alt="img4"/>4</a>
<a href="#" title="img5"><img src="data1/tooltips/img5.jpg" alt="img5"/>5</a>
<a href="#" title="img6"><img src="data1/tooltips/img6.jpg" alt="img6"/>6</a>
<a href="#" title="img7"><img src="data1/tooltips/img7.jpg" alt="img7"/>7</a>
</div></div>
<a class="wsl" href="http://wowslider.com">Javascript Gallery Download by WOWSlider.com v2.7.1</a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>